package keary.synthnotes;
import java.io.*;
import com.softsynth.jsyn.*;
/**************
** WARNING - this code automatically generated by Wire.
** The real source is probably a Wire patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Wire.
**
** Wire is available from: http://www.softsynth.com/wire/
*/
public class Atut04_mod_offset6765 extends SynthNote
{
    // Declare units and ports.
    SawtoothOscillatorBL sawOscBl;
    LineOut lineOut;
    SineOscillator sinOsc;
    AddUnit add;

    public Atut04_mod_offset6765()
    {
        this( Synth.getSharedContext() );
    }
    public Atut04_mod_offset6765( SynthContext synthContext )
    {
        super( synthContext );
        // Create unit generators.
        add( sawOscBl = new SawtoothOscillatorBL(synthContext) );
        add( lineOut = new LineOut(synthContext) );
        add( sinOsc = new SineOscillator(synthContext) );
        add( add = new AddUnit(synthContext) );
        // Connect units and ports.
        sawOscBl.phase.set( 0, -0.29386549377533566 );
        sawOscBl.amplitude.set( 0, 0.999969482421875 );
        sawOscBl.output.connect( 0, lineOut.input, 1);
        sawOscBl.output.connect( lineOut.input);
        sinOsc.frequency.set( 0, 2584.0 );
        sinOsc.phase.set( 0, 0.4305789618341794 );
        sinOsc.amplitude.set( 0, 1597.0 );
        sinOsc.output.connect( add.inputA);
        add.inputB.set( 0, 1.0 );
        add.output.connect( sawOscBl.frequency);
    }
    
    public void setStage( int time, int stage )
    {
        switch( stage )
        {
        case 0:
            start( time );
            break;
        case 1:
            break;
        default:
            break;
        }
    }
}
