package keary.synthnotes;

import java.io.*;
import com.softsynth.jsyn.*;

/**************
** WARNING - this code automatically generated by Wire.
** The real source is probably a Wire patch.
** Do NOT edit this file unless you copy it to another directory and change the name.
** Otherwise it is likely to get clobbered the next time you
** export Java source code from Wire.
**
** Wire is available from: http://www.softsynth.com/wire/
*/
public class MyEnvelopedSawTritoImpSynthNote extends SynthNote
{
    // Declare units and ports.
    SawtoothOscillatorBL sawOscBl;
    TriangleOscillator triOsc;
    public SynthInput trifreq;
    public SynthInput triAmp;
    MultiplyUnit mult;
    ImpulseOscillatorBL impOscBl;
    public SynthInput impFreq;
    EnvelopePlayer envPlay;
    SynthEnvelope envelope;

    public MyEnvelopedSawTritoImpSynthNote()
    {
        this( Synth.getSharedContext() );
    }
    public MyEnvelopedSawTritoImpSynthNote( SynthContext synthContext )
    {
        super( synthContext );
        // Create unit generators.
        add( sawOscBl = new SawtoothOscillatorBL(synthContext) );
        add( triOsc = new TriangleOscillator(synthContext) );
        add( mult = new MultiplyUnit(synthContext) );
        add( impOscBl = new ImpulseOscillatorBL(synthContext) );
        add( envPlay = new EnvelopePlayer(synthContext) );
        double[] envelopeData = {
            0.22543621423341687, 0.8583333333333333, 
            0.16011870873086562, 0.6166666666666667, 
            0.7011632379557782, 0.6083333333333333, 
            1.7761073385012276, 0.0, 
        };
        envelope = new SynthEnvelope( synthContext, envelopeData );
        envelopeData = null;
        envelope.setSustainLoop( -1, -1 );
        envelope.setReleaseLoop( -1, -1 );
        // Connect units and ports.
        sawOscBl.phase.set( 0, 0.2918434202322899 );
        sawOscBl.output.connect( mult.inputA);

        addPort( amplitude = sawOscBl.amplitude, "amplitude" );
        amplitude.setup( 0.0, 0.5, 1.0 );

        addPort( frequency = sawOscBl.frequency, "frequency" );
        frequency.setup( 0.0, 329.62850374278463, 10.0 );
        addPort( output = impOscBl.output, "output" );
        triOsc.phase.set( 0, 0.03242630399765967 );
        triOsc.output.connect( mult.inputB);

        addPort( trifreq = triOsc.frequency, "trifreq" );
        trifreq.setup( 0.0, 2000.0, 2000.0 );

        addPort( triAmp = triOsc.amplitude, "triAmp" );
        triAmp.setup( 0.0, 5.0, 1.0 );
        mult.output.connect( envPlay.amplitude);
        impOscBl.phase.set( 0, 0.3782312924261344 );

        addPort( impFreq = impOscBl.frequency, "impFreq" );
        impFreq.setup( 0.0, 100.0, 1000.0 );
        envPlay.rate.set( 0, 1.0 );
        envPlay.output.connect( impOscBl.amplitude);
    }
    
    public void setStage( int time, int stage )
    {
        switch( stage )
        {
        case 0:
            envPlay.envelopePort.clear( time );
            envPlay.envelopePort.queueOn( time, envelope );
            start( time );
            break;
        case 1:
            envPlay.envelopePort.queueOff( time, envelope );
            break;
        default:
            break;
        }
    }
}
